### ISSUE TITLE
Pretrained Weights 

### ISSUE THREAD

**Issue by abhigoku10** [LiWentomng/boxlevelset#1]
@LiWentomng  thanks for opesourcing the code based can you please share the pre trained model on google drive or on one drive 

Thanks in adavance

**Comment by LiWentomng** [comment]
@abhigoku10   Because this code has been refined, like **vars name**, there are some differences between the pretrained weights and this code. The pretrained weights can not be load rightly.  I will re-train and upload the matched weights timely.   And our method also has been refined for the general COCO dataset, recently.

**Comment by abhigoku10** [comment]
@LiWentomng thanks a lot for response, definitely will wait for the pre-trained weights to test the architecture . can you please give the tentative time for the update

**Comment by abhigoku10** [comment]
@LiWentomng  any update on this thread , can you share the pretrained weights and update the code base ?
